@baseUrl = http://localhost:8080

### Login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "codigo": "20210274",
  "contrasenia": "1234"
}


###

### Obtener Usuario Autenticado
GET {{baseUrl}}/usuario
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiY29kaWdvIjoiMjAyMTAyNzQifQ.0kkGgzXiUE8Ys5kM8jdfdU2QCzIxuzO0TzFGtbXRMuw
###

### Crear Usuario
POST {{baseUrl}}/usuarios
Content-Type: application/json

{
  "nombre": "Mariela Alca",
  "codigo": "20192005",
  "correo": "mariela@test.com",
  "celular": "902305536",
  "foto": "ruta/a/foto.jpg",
  "contrasenia": "123",
  "carrera_id": 10
}

###

### Cambiar Contraseña (Para Usuario Autenticado)
PUT {{baseUrl}}/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiY29kaWdvIjoiMjAyMTAyNzQifQ.0kkGgzXiUE8Ys5kM8jdfdU2QCzIxuzO0TzFGtbXRMuw
Content-Type: application/json

{
  "newContrasenia": "1234",
  "repetirContrasenia": "1234"
}


###


### Generar Contraseña Temporal y Enviar por Correo
POST {{baseUrl}}/usuario/contrasenia-olvidada
Content-Type: application/json

{
  "correo": "20210274@aloe.ulima.edu.pe"
}

###
